# fly.toml app configuration file generated for ollanbackend-jr1d3g on 2025-07-12T21:23:18Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ollanbackend-jr1d3g'
primary_region = 'jnb'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
